tap 'anomalyco/tap', trusted: true
tap 'bajankristof/tap', trusted: true
tap 'common-fate/granted', trusted: true

# Shell
brew 'bash'
brew 'mise'
brew 'starship'
brew 'stow'

# Neovim
brew 'nvim'
brew 'fd'
brew 'fzf'
brew 'ripgrep'
brew 'tree-sitter'
brew 'tree-sitter-cli'

# Tools
brew 'awscli'
brew 'btop'
brew 'difftastic'
brew 'common-fate/granted/granted', trusted: true
brew 'helm'
brew 'httpie'
brew 'jq'
brew 'luarocks'
brew 'tealdeer'
brew 'yq'
brew 'zoxide'

# Goodies
brew 'bajankristof/tap/hopkey', trusted: true

# Libraries
brew 'libyaml' # ruby-lsp dependency

# Casks
cask 'dotnet-sdk'
cask 'font-jetbrains-mono-nerd-font'
cask 'ghostty'
