alias dps='docker ps'
alias dlsi='docker image ls'
alias drmi='docker rmi'
alias drun='docker run --rm -it'
alias dexec='docker exec -it'
alias dlogs='docker logs'
alias dstats='docker stats'
alias dbuild='docker build'
alias dbuildx='docker buildx'

alias dcbuild='docker compose build'
alias dcup='docker compose up'
alias dcupd='docker compose up -d'
alias dcdown='docker compose down'
alias dcrun='docker compose run --rm -it'
alias dcrestart='docker compose restart'
alias dcexec='docker compose exec -it'
alias dclogs='docker compose logs'
