tap 'common-fate/granted'
tap 'hashicorp/tap'

brew 'stow'
brew 'jq'
brew 'yq'
brew 'asdf'
brew 'awscli'
brew 'bkt'
brew 'bash'
brew 'fzf'
brew 'go'
brew 'granted'
brew 'nvim'
brew 'ripgrep'
brew 'fd'
brew 'luarocks'
brew 'lua-language-server'
brew 'thefuck'

brew 'hashicorp/tap/packer'
brew 'hashicorp/tap/terraform'
brew 'hashicorp/tap/terraform-ls'

cask 'font-jetbrains-mono-nerd-font'
