#!/bin/zsh

ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

# Install Homebrew
bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

# Install Homebrew formulae
brew install thefuck
brew install jq yq
brew install awscli granted
brew tap homebrew/cask-fonts
brew install --cask font-jetbrains-mono-nerd-font

# Install oh-my-zsh
sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

# Install oh-my-zsh plugins
git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
git clone https://github.com/zsh-users/zsh-syntax-highlighting $ZSH_CUSTOM/plugins/zsh-syntax-highlighting

# Install oh-my-zsh theme
rm $ZSH_CUSTOM/themes/warp.zsh-theme
ln -s $(realpath resources/warp.zsh-theme) $ZSH_CUSTOM/themes/warp.zsh-theme

# Setup .zshrc
sed -i -E 's/ZSH_THEME=".*"/ZSH_THEME="warp"/' ~/.zshrc
sed -i -E 's/plugins=(.*)/plugins=(git zsh-autosuggestions zsh-syntax-highlighting)/' ~/.zshrc
echo '$(eval thefuck --alias)' >> ~/.zshrc

open resources/Warp.terminal
