#!/bin/zsh

ZSH_CUSTOM=${ZSH_CUSTOM:-~/.oh-my-zsh/custom}

set -e

__dir="${0:a:h}"

function blue {
  echo -e "\033[1;34m$1\033[0m"
}

function green {
  echo -e "\033[1;32m$1\033[0m"
}

# Install Homebrew
if ! command -v brew &> /dev/null; then
    blue 'Installing Homebrew...'
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
    green 'done'
    echo ''
fi

# Install Homebrew formulae
blue 'Installing Homebrew formulae...'
brew bundle --file="${__dir}/Brewfile"
green 'done'
echo ''

# Install Oh My Zsh
if [[ ! -d ~/.oh-my-zsh ]]; then
  blue 'Installing Oh My Zsh...'
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  green 'done'
  echo ''
fi

# Install Oh My Zsh plugins
if [[ ! -d $ZSH_CUSTOM/plugins/zsh-autosuggestions ]]; then
  blue 'Installing Oh My Zsh autosuggestions...'
  git clone https://github.com/zsh-users/zsh-autosuggestions $ZSH_CUSTOM/plugins/zsh-autosuggestions
  green 'done'
  echo ''
fi

if [[ ! -d $ZSH_CUSTOM/plugins/zsh-syntax-highlighting ]]; then
  blue 'Installing Oh My Zsh syntax highlighting...'
  git clone https://github.com/zsh-users/zsh-syntax-highlighting $ZSH_CUSTOM/plugins/zsh-syntax-highlighting
  green 'done'
  echo ''
fi

# Install Oh My Zsh theme
blue 'Installing Oh My Zsh theme...'
rm $ZSH_CUSTOM/themes/free2stray.zsh-theme
ln -s "${__dir}/assets/free2stray.zsh-theme" $ZSH_CUSTOM/themes/free2stray.zsh-theme
green 'done'
echo ''

# Install Ghostty configuration
blue 'Installing Ghostty configuration...'
rm -rf ~/.config/ghostty
ln -s "${__dir}/assets/ghostty" ~/.config/ghostty
green 'done'
echo ''

# Setup .zshrc
blue 'Setting up .zshrc...'
rm -f ~/.zshrc
rm -rf ~/.zshrc.d
ln -s "${__dir}/assets/zshrc.sh" ~/.zshrc
ln -s "${__dir}/assets/zshrc.d" ~/.zshrc.d
open "${__dir}/assets/free2stray.terminal"
green 'done'
