-G
--fullscreen
--adaptive-sync
--env LD_PRELOAD=''
--env PROTON_ENABLE_WAYLAND=1
# --env PROTON_FSR4_INDICATOR=1
--env PROTON_FSR4_UPGRADE=1
--env PROTON_FSR4_RDNA3_UPGRADE=1
--env PROTON_ENABLE_HDR=1
--env ENABLE_HDR_WSI=1
